// <auto-generated />
namespace TheBookshelf.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Deletedaddeddate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Deletedaddeddate));
        
        string IMigrationMetadata.Id
        {
            get { return "202007021511357_Deleted added date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
