// <auto-generated />
namespace TheBookshelf.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Changedfileurltocoverurl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changedfileurltocoverurl));
        
        string IMigrationMetadata.Id
        {
            get { return "202007021248508_Changed fileurl to coverurl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
