// <auto-generated />
namespace TheBookshelf.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class removedprofileurl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedprofileurl));
        
        string IMigrationMetadata.Id
        {
            get { return "202007191439492_removed profile url"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
